# Generated by Django 4.1.4 on 2022-12-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=5000)),
                ('title', models.CharField(default='', max_length=200)),
                ('source', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExcerptInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(default=0)),
                ('diversity', models.IntegerField(default=0)),
                ('text_length', models.IntegerField(default=0)),
                ('topic', models.CharField(default='', max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.excerpt')),
            ],
        ),
    ]
