# Generated by Django 4.1.4 on 2023-01-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_remove_excerptinfo_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collections',
            field=models.ManyToManyField(blank=True, to='api.category'),
        ),
    ]
