# Generated by Django 4.1.4 on 2023-01-21 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_collections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Collection',
        ),
        migrations.RemoveField(
            model_name='excerptinfo',
            name='category',
        ),
        migrations.AddField(
            model_name='excerpt',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.collection'),
        ),
        migrations.AddField(
            model_name='excerpt',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
