# Generated by Django 4.1.4 on 2023-01-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_category_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='text',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
