# Generated by Django 4.1.5 on 2023-03-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_excerpt_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, default="", max_length=5000, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
        ),
    ]
